# Generated by Django 4.2.1 on 2024-04-01 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RA', '0003_member_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='joined_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='phone_number',
            field=models.IntegerField(null=True),
        ),
    ]
